### ISSUE TITLE
Full finetuning / 8bit lora finetuning 지원 여부

### ISSUE THREAD

**Issue by bodybreaker** [davidkim205/komt#1]
좋은 내용 공유해 주셔서 감사합니다.

komt 모델을 base로 full finetuning 이나 / 8bit lora finetuning도 가능한지 여부를 여쭤보고싶습니다.

감사합니다.

**Comment by davidkim205** [comment]
full finetuning과 8bit lora는 다음주정도 코드를 올리겠습니다 News or Update 를 통해 업데이트를 확인하시면 될것 같습니다

**Comment by davidkim205** [comment]
model_max_length에 대한 실험결과 4k보다 2k가 훨씬 좋은 결과가 좋았습니다. 가설을 세우기로는 데이터가 4k가 되는경우가 별로 없어서 나쁘지 않았을까 하고 생각하고 있습니다.
max_new_tokens는 크게 생각하지 않았고 실험한결과 대략 512면 어느정도 대답을 만족스럽게 하기때문에 설정하였습니다. 원하는 값으로 변경해도 문제 없습니다.

**Comment by davidkim205** [comment]
4bit/8bit 코드를 추가했습니다. 최신 코드를 받아서 학습하시면 됩니다.
[7867909607c4d52437c24cbb225408baf72ae656
](https://github.com/davidkim205/komt/commit/7867909607c4d52437c24cbb225408baf72ae656)
