### ISSUE TITLE
komt_squad.json 데이터 관련 질문드립니다.

### ISSUE THREAD

**Issue by siryuon** [davidkim205/komt#3]
안녕하세요. 연구 자료 잘 보았습니다. 공유 감사합니다.

다름이 아니라, 질문이 하나 있는데요, KorQuad 데이터셋을 가져오실때, context를 같이 넣지 않은 이유가 있을까요?

단순히 질문-답변의 형태에 집중한 것으로 볼 수 있을까요?

**Comment by davidkim205** [comment]
task를 mrc에서 opendomain qa를 변경했다고 보면 좋을것 같습니다. context를 넣으면 mrc task로 얼마나 지문에서 답을 찾는지를 보는것이라면 opendomain qa는 질문만으로 얼마나 정답에 가까운 답변을 하는지를 추론하는 task이기 때문입니다.
