### ISSUE TITLE
13b lora training 파라미터 공유 문의

### ISSUE THREAD

**Issue by SOSONAGI** [davidkim205/komt#4]
안녕하세요!
우선 좋은 모델 공유해 주셔서 감사 드립니다!
Polyglot이후 한국어 inference가 가장 완벽히 되는 거 같습니다 감사합니다!
다름이 아니오라, 현재 공유주신 finetune training 부분이 7b에 맞춰져 있는거 같은데 13b 학습 시 참고가능할 파라미터 수치가 있는지 궁금합니다..!
13b 학습 후 체크포인트 인퍼런스를 해봤는데 성능이 너무 떨어져서 여쭙니다..!
감사합니다!

**Comment by davidkim205** [comment]
파라미터는 7b와 동일하게 했는데 lora인가요? 아니면 full fine-tuning인가요? 
그리고 데이터에 따라 lr을 변경해야하는데 어떤 데이터를 사용하였나요?

**Comment by SOSONAGI** [comment]
안녕하세요 답변 감사 드립니다!
davidkim205님께서 안내주신 finetune_with_lora로 진행했고, 
default를 davidkim205/komt-llama2-13b-v1으로 변경하였습니다.
또한, finetune_with_lora.py 파일 내 gpu 사용을 auto로 변경하였고 그 외 하이퍼파라미터는 변경하지 않았습니다.
dataset 또한 해당 레포 폴더 내 komt_squad 로 진행하였습니다.
lr을 별도로 변경하지는 않았습니다..
13b로 변경 시 특별히 추가적으로 조언해 주실 부분이 있으시다면 안내해 주시면 감사하겠습니다..!
 감사합니다.

**Comment by davidkim205** [comment]
최적의 성능을 올릴수 있도록 finetune_with_lora.py를 수정했습니다.자세한 것은 아래 commit을 확인하시면 됩니다.
간단히 설명을 하면 기존fp16-> fp32, lr을 3e-5 -> 1e-6, max_steps을  1000으로 하였습니다.
lora모델의 경우 학습을 많이 한다고 좋은 결과가 나오는것이 아니기때문 max_steps 낮게 두셔도 됩니다.
추가로 10, 100 step별로 결과를 첨부하니 참고하세요.
https://github.com/davidkim205/komt/commit/2fc703996de46991ea1bd53f8262108ec97ab99a

### checkpoint-10
{"id": 1, "instruction": "GPT 모델이 수행할 수 없는 두 가지 행동의 예를 제시하십시오.\n", "result": "1. GPT 모델은 실제 시간을 경험하거나 외부 환경에 대한 직접적인 정보를 수집할 수 없습니다. 예를 들어, \"오늘의 날씨는 어떤가요?\"라는 질문에 대해서는 현재 날씨 정보를 제공할 수 없습니다.\n\n2. GPT 모델은 직접적인 움직임이나 신체 활동을 수행할 수 없습니다. 예를 들어, \"내일 운동을 할 거야\"라는 문장을 생성하는 것은 가능하지만, 실제로 운동을 수행하는 능력은 없습니다.</s>"}
### checkpoint-100
{"id": 1, "instruction": "GPT 모델이 수행할 수 없는 두 가지 행동의 예를 제시하십시오.\n", "result": "1. GPT 모델이 수행할 수 없는 첫 번째 행동은 실제 시간에 따라 상황을 판단하고 결정하는 것입니다. GPT 모델은 대부분의 입력에 대해 정확한 출력을 생성하지만, 시간 의존적인 결정이 필요한 경우에는 모델이 실시간 상황을 고려하여 최적의 결정을 내리는 능력이 부족합니다. 예를 들어, \"내일의 날씨는 어떠한가?\"라는 질문에 대한 출력을 생성하는 경우, GPT 모델은 실시간으로 날씨 정보를 업데이트하는 기능을 제공하지 못합니다.\n\n2. 두 번째로, GPT 모델은 물리적인 상호작용을 수행할 수 없습니다. GPT 모델은 텍스트 기반의 입력과 출력을 처리하는 데 특화되어 있으며, 물리적인 장치나 시스템을 제어하거나 상호작용하는 능력이 부족합니다. 예를 들어, \"컴퓨터의 전원을 켜/끄세요\"라는 명령을 내리는 경우, GPT 모델은 직접 컴퓨터의 전원을 제어하는 기능을 수행할 수 없습니다. 이러한 상호작용은 실제 컴퓨터 제어 시스템과 같은 다른 기술과 함께 사용되어야 합니다.</s>"}

**Comment by davidkim205** [comment]
추가 문의 사항이 있으면 이슈를 다시 열어주세요.

**Comment by SOSONAGI** [comment]
답변 감사합니다!
