### ISSUE TITLE
function calling 모델을 만드는 것을 로드맵으로 하는것은 어떨까요?

### ISSUE THREAD

**Issue by ssifood** [davidkim205/komt#9]
안녕하십니까 항상 열심히 지식 도둑중인 사람입니다.

LLM으로 RAG시 fucnction calling이 필요할때가 있습니다.

llama2등 fucntion calling을 적용해서 공개 하는경우도 종종 있는데.

호옥시 향후 로드맵으로

1. function calling
추천드립니다.

참고자료
https://github.com/RonanKMcGovern/qlora-functions
https://huggingface.co/Trelis
https://huggingface.co/models?search=function

지식도둑주제에 바라는게 많은 점 죄송합니다.

항상 행님의 건강과 행복을 빕니다.

**Comment by davidkim205** [comment]
요즘 새로운 모델준비로 정신이 없었네요.. 어느정도 마무리되는 시점에 보겠습니다. 추천해줘서 감사합니다.

**Comment by ssifood** [comment]
새로운 모델은 뭡니까?? 궁금합니다 행님

현 랭킹 1위는 qwen 1.5 로 빚은 smaug 70B로 알고 있습니다 행님

**Comment by ssifood** [comment]
https://huggingface.co/datasets/heegyu/glaive-function-calling-v2-ko

gpt형 function call용 한글데이터셋입니다. 행님

**Comment by davidkim205** [comment]
공유 감사합니다~ 조만간 만들면 오픈하도록 하겠습니다~
